/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editordetexto;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author fampa
 */
public class editorDeTexto extends javax.swing.JFrame {
    public static String tipo;
   public static String nombre;

    /**
     * Creates new form editorDeTexto
     */
    public editorDeTexto() {
        initComponents();
        
        doc = tp_texto.getStyledDocument();
        estilo = tp_texto.addStyle("miEstilo", null);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) combo_tipodeletra.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String fontNames[] = ge.getAvailableFontFamilyNames();
        for (int i = 0; i < fontNames.length; i++) {
            modelo.addElement(fontNames[i]);
        }
        combo_tipodeletra.setModel(modelo);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_texto = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        combo_tipodeletra = new javax.swing.JComboBox<>();
        combo_tamaño = new javax.swing.JComboBox<>();
        negrita_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        delado_btn = new javax.swing.JButton();
        subrayado_btn = new javax.swing.JButton();
        resaltador_btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        colorletra_btn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        abrirarch_btn = new javax.swing.JButton();
        guardararch_btn = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tp_texto);

        jToolBar1.setRollover(true);

        jToolBar1.add(combo_tipodeletra);

        combo_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18", "24", "36", "48", "60", "72" }));
        jToolBar1.add(combo_tamaño);

        negrita_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        negrita_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        negrita_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        negrita_btn.setRequestFocusEnabled(false);
        negrita_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negrita_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(negrita_btn);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setMaximumSize(new java.awt.Dimension(7, 32767));
        jSeparator1.setPreferredSize(new java.awt.Dimension(7, 0));
        jToolBar1.add(jSeparator1);

        delado_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        delado_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        delado_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        delado_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delado_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(delado_btn);

        subrayado_btn.setFocusable(false);
        subrayado_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subrayado_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        subrayado_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subrayado_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(subrayado_btn);

        resaltador_btn.setFocusable(false);
        resaltador_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resaltador_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resaltador_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resaltador_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(resaltador_btn);
        jToolBar1.add(jSeparator2);

        colorletra_btn.setMaximumSize(new java.awt.Dimension(76, 11));
        colorletra_btn.setMinimumSize(new java.awt.Dimension(76, 11));
        colorletra_btn.setPreferredSize(new java.awt.Dimension(76, 11));
        colorletra_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorletra_btnMouseClicked(evt);
            }
        });

        jToolBar2.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorletra_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardararch_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirarch_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorletra_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(abrirarch_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardararch_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resaltador_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltador_btnMouseClicked
        // TODO add your handling code here:
         try {

            StyleConstants.setBackground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.yellow)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_resaltador_btnMouseClicked

    private void colorletra_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorletra_btnMouseClicked
        // TODO add your handling code here:
         try {

            StyleConstants.setForeground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.red)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_colorletra_btnMouseClicked

    private void negrita_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negrita_btnMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setBold(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_negrita_btnMouseClicked

    private void delado_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delado_btnMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            StyleConstants.setItalic(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_delado_btnMouseClicked

    private void subrayado_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subrayado_btnMouseClicked
        // TODO add your handling code here:
         try {
            StyleConstants.setUnderline(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_subrayado_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editorDeTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirarch_btn;
    private javax.swing.JButton colorletra_btn;
    private javax.swing.JComboBox<String> combo_tamaño;
    private javax.swing.JComboBox<String> combo_tipodeletra;
    private javax.swing.JButton delado_btn;
    private javax.swing.JButton guardararch_btn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton negrita_btn;
    private javax.swing.JButton resaltador_btn;
    private javax.swing.JButton subrayado_btn;
    private javax.swing.JTextPane tp_texto;
    // End of variables declaration//GEN-END:variables

    StyledDocument doc;
    Style estilo;

}

