/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editordetexto;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author fampa
 */
public class editorDeTexto extends javax.swing.JFrame {

    public static String tipo;
    public static String nombre;

    /**
     * Creates new form editorDeTexto
     */
    public editorDeTexto() {
        initComponents();

        doc = tp_texto.getStyledDocument();
        estilo = tp_texto.addStyle("miEstilo", null);
        tipo = "----";

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) combo_tipodeletra.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String fontNames[] = ge.getAvailableFontFamilyNames();
        for (int i = 0; i < fontNames.length; i++) {
            modelo.addElement(fontNames[i]);
        }
        combo_tipodeletra.setModel(modelo);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_texto = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        combo_tipodeletra = new javax.swing.JComboBox<>();
        combo_tamaño = new javax.swing.JComboBox<>();
        negrita_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        delado_btn = new javax.swing.JButton();
        subrayado_btn = new javax.swing.JButton();
        resaltador_btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        colorletra_btn = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        abrirarch_btn = new javax.swing.JButton();
        guardararch_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(tp_texto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 121, 909, 494));

        jToolBar1.setRollover(true);

        combo_tipodeletra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_tipodeletraItemStateChanged(evt);
            }
        });
        jToolBar1.add(combo_tipodeletra);

        combo_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18", "24", "36", "48", "60", "72" }));
        combo_tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tamañoActionPerformed(evt);
            }
        });
        jToolBar1.add(combo_tamaño);

        negrita_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        negrita_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        negrita_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        negrita_btn.setRequestFocusEnabled(false);
        negrita_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negrita_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(negrita_btn);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setAlignmentX(0.0F);
        jSeparator1.setMaximumSize(new java.awt.Dimension(7, 32767));
        jSeparator1.setPreferredSize(new java.awt.Dimension(7, 0));
        jToolBar1.add(jSeparator1);

        delado_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        delado_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        delado_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        delado_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delado_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(delado_btn);

        subrayado_btn.setFocusable(false);
        subrayado_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subrayado_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        subrayado_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        subrayado_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subrayado_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(subrayado_btn);

        resaltador_btn.setFocusable(false);
        resaltador_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resaltador_btn.setMaximumSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setMinimumSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setPreferredSize(new java.awt.Dimension(10, 8));
        resaltador_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resaltador_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resaltador_btnMouseClicked(evt);
            }
        });
        jToolBar1.add(resaltador_btn);
        jToolBar1.add(jSeparator2);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 43, 667, 66));

        colorletra_btn.setText("Color");
        colorletra_btn.setMaximumSize(new java.awt.Dimension(76, 11));
        colorletra_btn.setMinimumSize(new java.awt.Dimension(76, 11));
        colorletra_btn.setPreferredSize(new java.awt.Dimension(76, 11));
        colorletra_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorletra_btnMouseClicked(evt);
            }
        });
        getContentPane().add(colorletra_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 43, 84, 31));

        jToolBar2.setRollover(true);
        getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 43, 90, 40));

        abrirarch_btn.setText("Abrir Archivo");
        abrirarch_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirarch_btnMouseClicked(evt);
            }
        });
        getContentPane().add(abrirarch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 43, 124, 33));

        guardararch_btn.setText("Guardar");
        guardararch_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardararch_btnMouseClicked(evt);
            }
        });
        getContentPane().add(guardararch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 82, 124, 27));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Size");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 37, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Font");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 37, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resaltador_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltador_btnMouseClicked
        // TODO add your handling code here:
        try {

            StyleConstants.setBackground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.yellow)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_resaltador_btnMouseClicked

    private void colorletra_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorletra_btnMouseClicked
        // TODO add your handling code here:
        try {

            StyleConstants.setForeground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.red)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_colorletra_btnMouseClicked

    private void negrita_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negrita_btnMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setBold(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_negrita_btnMouseClicked

    private void delado_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delado_btnMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            StyleConstants.setItalic(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_delado_btnMouseClicked

    private void subrayado_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subrayado_btnMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setUnderline(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_subrayado_btnMouseClicked

    private void combo_tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tamañoActionPerformed
        // TODO add your handling code here:
        StyleConstants.setFontSize(estilo, Integer.parseInt(combo_tamaño.getSelectedItem().toString()));
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_combo_tamañoActionPerformed

    private void combo_tipodeletraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_tipodeletraItemStateChanged
        // TODO add your handling code here:
        StyleConstants.setFontFamily(estilo, combo_tipodeletra.getSelectedItem().toString());
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_combo_tipodeletraItemStateChanged

    private void guardararch_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardararch_btnMouseClicked
        JFileChooser jfc = new JFileChooser();
        if (tipo.equals("Administrador")) {
            jfc.setCurrentDirectory(new File("Z"));
        } else {
            jfc.setCurrentDirectory(new File("Z/" + nombre));
        }
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Text file", "txt");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;

        try {
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Text file")) {
                    fichero = new File(jfc.getSelectedFile().getPath() + ".txt");
                } else {
                    fichero = jfc.getSelectedFile();
                }

                fw = new FileOutputStream(fichero);
                bw = new ObjectOutputStream(fw);
                Documento d = new Documento(tp_texto, doc, estilo);
                bw.writeObject(d);
                bw.flush();

                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (bw != null) {
                    bw.close();
                }
                if (fw != null) {
                    fw.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_guardararch_btnMouseClicked

    private void abrirarch_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirarch_btnMouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        try {
            JFileChooser jfc = new JFileChooser();
            if (tipo.equals("Administrador")) {
                jfc.setCurrentDirectory(new File("Z"));
            } else {
                jfc.setCurrentDirectory(new File("Z/" + nombre));
            }
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("text file", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                tp_texto.setText("");
                Documento temp = (Documento) objeto.readObject();
                tp_texto.setText(((Documento) temp).getPanel().getText());
                tp_texto.setDocument(((Documento) temp).getDoc());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El archivo no existe.");
        } finally {
            try {
                if (objeto != null) {
                    objeto.close();
                }
                if (entrada != null) {
                    entrada.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_abrirarch_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editorDeTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirarch_btn;
    private javax.swing.JButton colorletra_btn;
    private javax.swing.JComboBox<String> combo_tamaño;
    private javax.swing.JComboBox<String> combo_tipodeletra;
    private javax.swing.JButton delado_btn;
    private javax.swing.JButton guardararch_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton negrita_btn;
    private javax.swing.JButton resaltador_btn;
    private javax.swing.JButton subrayado_btn;
    private javax.swing.JTextPane tp_texto;
    // End of variables declaration//GEN-END:variables

    StyledDocument doc;
    Style estilo;

}
